In [8]:
import numpy as np

# create one dimensional array
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

# create two dimensional array
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

# to populate an array with all zeros call np.zeros. to populate an array with all ones call np.ones
zeros = np.zeros([2, 3])
print("zero values", zeros)

sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers) # np.arange generates a sequence that includes the lower bond 5 but not the upper bond 12

# populate arrays with random numbers
random_integers_btn_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_btn_50_and_100)

# create a random floating point value btn 0.0 and 1.0
random_floating_point_value = np.random.random(6)
print(random_floating_point_value)



[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]
[[ 6  5]
 [11  7]
 [ 4  8]]
zero values [[0. 0. 0.]
 [0. 0. 0.]]
[ 5  6  7  8  9 10 11]
[86 83 86 56 68 97]
[0.20440785 0.67946212 0.33200465 0.27244891 0.1228148  0.47610913]


Mathematical operations on numpy operands
Broadcasting - virtually expands the smaller operands to dimensions comaptible for linear algebra


In [10]:
# adding 2.0 to the value of every item created i the code cell
random_floats_btn_2_and_3 = random_floating_point_value + 2.0
print(random_floats_btn_2_and_3)

# broadcasting to multiply each cell in an array by 3
random_integers_btn_150_and_300 = random_integers_btn_50_and_100 * 3
print(random_integers_btn_150_and_300)


[2.20440785 2.67946212 2.33200465 2.27244891 2.1228148  2.47610913]
[258 249 258 168 204 291]


Create a Linear Dataset